In [1]:
import torch
import numpy as np

#A partir de una lista de Python
list = ([1,2],[3,4],[5,6])
tensor1=torch.tensor(list)
print("T1:", tensor1)

#A partir de los datos directamente
tensor2=torch.tensor([[[1, 2, 3],[4, 5, 6]],[[1, 2, 3],[4, 5, 6]]])
print("T2:",tensor2)

#A partir de un array numpy
tensor3=torch.tensor(np.array([1,2,3,4]))
print("T3:",tensor3)

#Usando una operación de creación de tensores
tensor4=torch.rand(2,3)
print("T4:",tensor4)

T1: tensor([[1, 2],
        [3, 4],
        [5, 6]])
T2: tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])
T3: tensor([1, 2, 3, 4])
T4: tensor([[0.8093, 0.0966, 0.0792],
        [0.7432, 0.5554, 0.5171]])


In [ ]:

#Un tensor de rango 2 (3,2) para tensor1
print(tensor1.size())

#Un tensor de rango 3 con las dimensiones (2,2,3) para tensor2
print(tensor2.size())

print(tensor3.size())
print(tensor4.size())

torch.Size([3, 2])
torch.Size([2, 2, 3])
torch.Size([4])
torch.Size([2, 3])


In [ ]:
#A los componentes de los tensores se puede acceder como usualmente en Python
print(tensor1[0])
print(tensor1[0,1])

#Con view se cambia las dimensiones y el rango del tensor
tensor5=torch.rand(2,4)
print(tensor5.size())

tensor6=tensor5.view(8)
print(tensor6.size())

tensor([1, 2])
tensor(2)
torch.Size([2, 4])
torch.Size([8])


In [ ]:
#Un tensor se puede crear con requires_grad=True para que torch.autograd registre las operaciones y realice la diferenciación automática
x = torch.tensor([2],dtype=torch.float,requires_grad=True)
print(x)
y = x.pow(3)
print(y)
y.backward()
#x.grad

print(y)
print(x.grad)

tensor([2.], requires_grad=True)
tensor([8.], grad_fn=<PowBackward0>)
tensor([8.], grad_fn=<PowBackward0>)
tensor([12.])


In [ ]:
#Comparación del tiempo en realizar una multiplicaión de matrices en la CPU y en la GPU
%%time
for i in range(500):
  x = torch.randn(1000,1000)
  y = torch.randn(1000,1000)
  z = torch.matmul(x,y)

CPU times: user 15.3 s, sys: 331 ms, total: 15.6 s
Wall time: 15.7 s


In [ ]:
#Se realiza la multiplicación en la GPU
%%time
#device = torch.device("cpu")
device = torch.device("cuda:0")
for i in range(500):
x = torch.randn(1000,1000,device = device)
  y = torch.randn(1000,1000,device = device)
  z = torch.matmul(x,y)

CPU times: user 1.52 s, sys: 995 ms, total: 2.52 s
Wall time: 6.61 s
