In [1]:
import torch


In [2]:
a = torch.Tensor([[1,2],[3,4]])
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [3]:
from torch.autograd import Variable
# The following variables will be differentiable
a = Variable(torch.Tensor([[1,2],[3,4]]), requires_grad=True)
print(a)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [4]:
y = torch.sum(a**2)
print(y)

tensor(30., grad_fn=<SumBackward0>)


In [5]:
y.backward() # compute gradients of y wrt a 

In [6]:
print(a.grad)  # print dy/da_ij = 2*a_ij for a_11, a_12, a21, a22

tensor([[2., 4.],
        [6., 8.]])


In [8]:
output_batch = model(train_batch)           # compute model output
loss = loss_fn(output_batch, labels_batch)  # calculate loss

optimizer.zero_grad()  # clear previous gradients
loss.backward()        # compute gradients of all variables wrt loss

optimizer.step() 

NameError: ignored

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class TwoLayerNet(nn.Module):
    def __init__(self, D_in, H, D_out): # 100, 50, 10
        """
        In the constructor we instantiate two nn.Linear modules and assign them as
        #member variables.

        D_in: input dimension
        H: dimension of hidden layer
        D_out: output dimension"""
        super(TwoLayerNet, self).__init__()
        self.linear1 = nn.Linear(D_in, H) # W_1
        self.linear2 = nn.Linear(H, D_out) # W_2

    def forward(self, x): # x (batch_size, D_in)
        """In the forward function we accept a Variable of input data and we must 
        return a Variable of output data. We can use Modules defined in the 
        constructor as well as arbitrary operators on Variables."""
        h_relu = F.relu(self.linear1(x))
        y_pred = self.linear2(h_relu)
        return y_pred  # return batch_size, D_out

In [ ]:
x(32, 100)*w_1(100, 50)= h__relu (32, 50)* w_2 (50, 10)->
y_pred (32, 10)

In [9]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [10]:
mnist = fetch_openml('mnist_784')
X = mnist.data
y = mnist.target

# Convertir las etiquetas de cadena a números enteros
y = y.astype(np.int)


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(
<ipython-input-10-48326f567bcf>:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = y.astype(n

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
# Escalar los valores de píxeles al rango [0, 1]
X_train = X_train / 255.0
X_test = X_test / 255.0


In [ ]:
class Perceptron:
    def __init__(self, lr=0.1, num_epochs=100):
        self.lr = lr
        self.num_epochs = num_epochs

    def train(self, X, y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0

        for epoch in range(self.num_epochs):
            for i in range(X.shape[0]):
                y_pred = self.predict(X[i])
                error = y[i] - y_pred
                self.weights += self.lr * error * X[i]
                self.bias += self.lr * error

    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        activation = np.where(linear_output >= 0, 1, 0)
        return activation


In [ ]:
perceptron = Perceptron(lr=0.1, num_epochs=10)
perceptron.train(X_train, y_train)

y_pred_train = perceptron.predict(X_train)
y_pred_test = perceptron.predict(X_test)

accuracy_train = accuracy_score(y_train, y_pred_train)
accuracy_test = accuracy_score(y_test, y_pred_test)

print("Accuracy en el conjunto de entrenamiento:", accuracy_train)
print("Accuracy en el conjunto de prueba:", accuracy_test)


In [11]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import tensorflow as tf
from tensorflow.keras import models, layers

mnist = fetch_openml('mnist_784')
X = mnist.data
y = mnist.target

# Convertir las etiquetas de cadena a números enteros
y = y.astype(np.int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Escalar los valores de píxeles al rango [0, 1]
X_train = X_train / 255.0
X_test = X_test / 255.0

model = models.Sequential()
model.add(layers.Dense(64, activation='relu', input_shape=(784,)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


model = models.Sequential()
model.add(layers.Dense(64, activation='relu', input_shape=(784,)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

accuracy_train = history.history['accuracy'][-1]
accuracy_test = history.history['val_accuracy'][-1]

print("Accuracy en el conjunto de entrenamiento:", accuracy_train)
print("Accuracy en el conjunto de prueba:", accuracy_test)


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(
<ipython-input-11-e3ed20c025df>:14: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = y.astype(

Epoch 1/10
1750/1750 [==============================] - 7s 4ms/step - loss: 0.2790 - accuracy: 0.9184 - val_loss: 0.1732 - val_accuracy: 0.9486
Epoch 2/10
1750/1750 [==============================] - 7s 4ms/step - loss: 0.1252 - accuracy: 0.9621 - val_loss: 0.1214 - val_accuracy: 0.9636
Epoch 3/10
1750/1750 [==============================] - 6s 3ms/step - loss: 0.0902 - accuracy: 0.9720 - val_loss: 0.1083 - val_accuracy: 0.9664
Epoch 4/10
1750/1750 [==============================] - 7s 4ms/step - loss: 0.0729 - accuracy: 0.9769 - val_loss: 0.1060 - val_accuracy: 0.9695
Epoch 5/10
1750/1750 [==============================] - 7s 4ms/step - loss: 0.0574 - accuracy: 0.9817 - val_loss: 0.0965 - val_accuracy: 0.9711
Epoch 6/10
1750/1750 [==============================] - 7s 4ms/step - loss: 0.0475 - accuracy: 0.9847 - val_loss: 0.0974 - val_accuracy: 0.9719
Epoch 7/10
1750/1750 [==============================] - 6s 3ms/step - loss: 0.0404 - accuracy: 0.9869 - val_loss: 0.0975 - val_accuracy:

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# Cargar los datos del conjunto MNIST
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Escalar los valores de píxeles al rango [0, 1]
X_train = X_train / 255.0
X_test = X_test / 255.0

# Aplanar las imágenes
X_train = X_train.reshape((X_train.shape[0], -1))
X_test = X_test.reshape((X_test.shape[0], -1))

# Convertir las etiquetas a one-hot encoding
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# Construir el modelo del MLP
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(784,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Entrenar el modelo
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Evaluar el modelo en el conjunto de prueba
loss, accuracy = model.evaluate(X_test, y_test)
print("Loss:", loss)
print("Accuracy:", accuracy)


11490434/11490434 [==============================] - 1s 0us/step
Epoch 1/10
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2737 - accuracy: 0.9205 - val_loss: 0.1437 - val_accuracy: 0.9568
Epoch 2/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1230 - accuracy: 0.9634 - val_loss: 0.0952 - val_accuracy: 0.9700
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0908 - accuracy: 0.9721 - val_loss: 0.0897 - val_accuracy: 0.9725
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0709 - accuracy: 0.9774 - val_loss: 0.0898 - val_accuracy: 0.9732
Epoch 5/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0595 - accuracy: 0.9815 - val_loss: 0.0803 - val_accuracy: 0.9738
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0492 - accuracy: 0.9841 - val_loss: 0.0983 - val_accuracy: 0.9704
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - l